language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
addons:
  apt:
    packages:
    - iverilog
install: 
  - pip install -r requirements.txt
script:
  - python suite.py -j -s -f
